# Generated by Django 4.0.4 on 2022-07-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='co_author_input',
            new_name='co_author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='choose_name',
        ),
        migrations.AlterField(
            model_name='ipmodel',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='CoAuthor',
        ),
    ]
