# Generated by Django 3.2.6 on 2022-04-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUsers',
        ),
    ]
